name: Continuous Integration (not deployment)

on:
  push:
    branches:
        - main

env:
  DOTNET_VERSION: '7.0.x'
  AZURE_WEBAPP_NAME: webapi-identity

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2017-latest
        env:
          SA_PASSWORD: YourStrong!Passw0rd
          ACCEPT_EULA: Y
          MSSQL_PID: Developer
        ports:
          - 1433:1433
        options: --name=mssql --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourStrong!Passw0rd' -Q 'SELECT 1'" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: check-out
        uses: actions/checkout@v3

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: Start SQL Server
        run: |
          docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=MyTestPassword" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2022-latest

      - name: Sleep for 5 seconds (wait for MSSQL to boot up)
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'

      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build app
        run: dotnet build -c Release --no-restore
      
      # - name: Run automated tests
      #   env:
      #     ConnectionStrings__DefaultConnection: "Server=localhost,1433;Initial Catalog=MyTestDb;User Id=sa;Password=MyTestPassword;"
      #   run: dotnet test -c Release --no-build

      - name: Create MS SQL Database
        run: |
          sudo apt-get update && sudo apt-get install -y mssql-tools
          /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourStrong!Passw0rd' -Q 'CREATE DATABASE test_db'
      
      - name: Run Tests
        run: dotnet test -c Release --no-build

      - name: Publish app
        run: dotnet publish -c Release -o ./out

      - name: Deploy to Azure Web Apps
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_SECRET }}
          package: ./out
      
      
      
 