name: Continuous Integration (not deployment)

on:
  push:
    branches:
        - main

env:
  DOTNET_VERSION: '7.0.x'
  AZURE_WEBAPP_NAME: webapi-identity

jobs:
  test-everywhere:
    name: Test Action on all platforms
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: MSSQL Suite
        uses: potatoqualitee/mssqlsuite@v1.7
        with:
          install: sqlengine, sqlpackage

      - name: Run sqlclient
        run: sqlcmd -S localhost -U sa -P dbatools.I0 -d tempdb -Q "SELECT @@version;"

      - name: Sleep for 5 seconds (wait for MSSQL to boot up)
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'

      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build app
        run: dotnet build -c Release --no-restore
      
      - name: Run automated tests
        run: dotnet test -c Release --no-build

      - name: Publish app
        run: dotnet publish -c Release -o ./out

      - name: Deploy to Azure Web Apps
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_SECRET }}
          package: ./out
      
      
      
 