name: Continuous Integration (not deployment)

on:
  push:
    branches:
        - main

env:
  DOTNET_VERSION: '7.0.x'
  AZURE_WEBAPP_NAME: webapi-identity

jobs:
  test-everywhere:
    name: Test Action on all platforms
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: MSSQL Suite
        uses: potatoqualitee/mssqlsuite@v1.7
        with:
          install: sqlengine, sqlpackage

      - name: Run sqlclient
        run: sqlcmd -S localhost -U sa -P dbatools.I0 -d tempdb -Q "SELECT @@version;"